In [7]:
with open('input/input_day7.txt') as file:
    bagsfile = file.read().splitlines()

In [456]:
import numpy as np

In [8]:
bagsfile[:5]

['dark olive bags contain 2 muted brown bags, 1 mirrored tomato bag, 4 bright black bags.',
 'faded coral bags contain 3 drab cyan bags, 1 light aqua bag.',
 'plaid plum bags contain 2 mirrored cyan bags.',
 'clear maroon bags contain 1 dotted turquoise bag, 3 dim lavender bags.',
 'plaid coral bags contain 3 posh fuchsia bags, 3 dotted beige bags, 2 wavy turquoise bags.']

In [427]:
bagbook = {}
bag_numbers = {}

for bag in bagsfile:
    bag_name = bag.split(' contain ')[0]
    contains = bag.split(' contain ')[1][:-1]
    con_bags = contains.split(', ')
    con_quant = [int(bag[0]) for bag in con_bags if bag != 'no other bags']
    con_bags = [bag[2:] for bag in con_bags if bag != 'no other bags']
    con_bags = list(map(lambda x: x+'s' if x[-1] != 's' else x, con_bags))
    
    
    bagbook[bag_name] = con_bags
    bag_numbers[bag_name] = con_quant

In [428]:
bag_numbers

{'dark olive bags': [2, 1, 4],
 'faded coral bags': [3, 1],
 'plaid plum bags': [2],
 'clear maroon bags': [1, 3],
 'plaid coral bags': [3, 3, 2],
 'mirrored indigo bags': [5, 5, 1, 4],
 'striped brown bags': [4, 5, 3, 3],
 'drab fuchsia bags': [5, 1, 4, 1],
 'light fuchsia bags': [3, 5],
 'plaid olive bags': [4, 4, 2, 2],
 'dotted green bags': [2],
 'dotted cyan bags': [1, 5],
 'muted magenta bags': [2],
 'mirrored cyan bags': [4, 3, 2, 1],
 'muted red bags': [2, 4],
 'clear indigo bags': [2, 4, 4],
 'plaid chartreuse bags': [3, 1],
 'wavy tan bags': [3],
 'bright crimson bags': [4],
 'pale yellow bags': [3, 2, 2],
 'pale tomato bags': [2],
 'dull salmon bags': [3],
 'light white bags': [2],
 'drab plum bags': [1],
 'shiny purple bags': [3, 1, 5],
 'pale red bags': [5, 2],
 'dull bronze bags': [2, 4, 3, 1],
 'wavy indigo bags': [2, 1],
 'vibrant silver bags': [5],
 'shiny tan bags': [4, 4, 5, 3],
 'dim yellow bags': [1],
 'faded white bags': [5, 3, 2, 5],
 'shiny tomato bags': [4, 2, 

In [256]:
bagbook

{'dark olive bags': ['muted brown bags',
  'mirrored tomato bag',
  'bright black bags'],
 'faded coral bags': ['drab cyan bags', 'light aqua bag'],
 'plaid plum bags': ['mirrored cyan bags'],
 'clear maroon bags': ['dotted turquoise bag', 'dim lavender bags'],
 'plaid coral bags': ['posh fuchsia bags',
  'dotted beige bags',
  'wavy turquoise bags'],
 'mirrored indigo bags': ['pale orange bags',
  'striped aqua bags',
  'dotted cyan bag',
  'muted coral bags'],
 'striped brown bags': ['faded green bags',
  'vibrant red bags',
  'drab black bags',
  'dark orange bags'],
 'drab fuchsia bags': ['shiny chartreuse bags',
  'dark orange bag',
  'drab blue bags',
  'bright chartreuse bag'],
 'light fuchsia bags': ['bright gold bags', 'clear indigo bags'],
 'plaid olive bags': ['striped indigo bags',
  'muted olive bags',
  'light gray bags',
  'wavy purple bags'],
 'dotted green bags': ['faded yellow bags'],
 'dotted cyan bags': ['light red bag', 'dark cyan bags'],
 'muted magenta bags': ['c

In [134]:
# gold containers
goldholders = [bag for bag in bagrules if 'shiny gold' in ''.join(bag.content)]

In [166]:
bagrules[177], bagrules[188]

(bagrule(name='vibrant red bags', content=[]),
 bagrule(name='dotted teal bags', content=['3 bright gray bags', '3 vibrant fuchsia bags']))

In [165]:
# direct gold containers
containers = [gh.name for gh in goldholders]

In [ ]:
------------------

In [409]:
pureblood = 0

for bagid in list(bagbook.keys()):
    
    childs = bagbook[bagid]
    childs = set(childs)
    
    family = True
    
    while 'shiny gold bags' not in childs:
        childs = [i for o in childs for i in bagbook[o]]  # put all found children of all nodes in 1 list
        childs = set(childs)
    
        if len(childs) == 0:
            family = False
            break
    
    if family == True:
        print(f'{bagid}: {str(family)}')
        pureblood += 1

dark olive bags: True
plaid coral bags: True
mirrored indigo bags: True
drab fuchsia bags: True
light fuchsia bags: True
plaid olive bags: True
dotted green bags: True
muted magenta bags: True
clear indigo bags: True
pale yellow bags: True
light white bags: True
drab plum bags: True
shiny purple bags: True
pale red bags: True
dull bronze bags: True
wavy indigo bags: True
shiny tan bags: True
faded white bags: True
striped white bags: True
drab white bags: True
plaid white bags: True
drab orange bags: True
light salmon bags: True
faded tomato bags: True
clear beige bags: True
mirrored bronze bags: True
muted purple bags: True
light coral bags: True
wavy beige bags: True
wavy turquoise bags: True
striped bronze bags: True
pale tan bags: True
dull black bags: True
mirrored aqua bags: True
shiny beige bags: True
shiny aqua bags: True
mirrored lavender bags: True
light tan bags: True
pale olive bags: True
muted chartreuse bags: True
shiny coral bags: True
faded bronze bags: True
bright aqua

In [410]:
pureblood

246

In [402]:
childs = bagbook['dark olive bags']
childs = set(childs)
childs

{'bright black bags', 'mirrored tomato bags', 'muted brown bags'}

In [ ]:
light aqua bags, 4 pale plum bags, 1 pale beige bag.

## test

In [789]:
numbers = bag_numbers['shiny gold bags']
numbers = np.asarray(numbers)
numbers

array([5, 2, 5, 5])

In [790]:
childs = bagbook['shiny gold bags']
childs

['dark salmon bags',
 'wavy purple bags',
 'dark cyan bags',
 'dull chartreuse bags']

In [791]:
generation = 0
endpoints = []
sumations = []

# gold fam has 5 generations 
for i in range(5):
    
    new_numbers = []
    for k, o in enumerate(childs):
        calc = np.array(bag_numbers[o]) * numbers[k]
        #print(bagbook[o])
        #print(bag_numbers[o], calc)
        
        if generation == 0:
            sumations.append((sum(bag_numbers[o]) * numbers[k]) + numbers[k])
        else:
            sumations.append(sum(bag_numbers[o]) * numbers[k])
                             
        new_numbers += calc.tolist()
         
    
    new_numbers = np.array(new_numbers)
    
    print(new_numbers)
    
    numbers = new_numbers
    
    childs = [i for o in childs for i in bagbook[o]] # put all found children of all nodes in 1 list
    
    print(f'----- generation {generation} -----')
    
    generation += 1

[15 25  5  6  2 15 10 15 15 25]
----- generation 0 -----
[45 25 25  6 75 30 75 45 75]
----- generation 1 -----
[100  25  25 100 150  75 225 150 180  45]
----- generation 2 -----
[200 100 300 200 100 100 150]
----- generation 3 -----
[200]
----- generation 4 -----


In [773]:
numbers

[]

In [780]:
sum(sumations)

2976

In [753]:
sum(sumations)

2976

In [440]:
x = [('dark salmon bags', 5),
 ('wavy purple bags', 2),
 ('dark cyan bags', 5),
 ('dull chartreuse bags', 5)]

for b in x:
    print(bagbook[b[0]])

['pale turquoise bags', 'faded tan bags', 'mirrored chartreuse bags']
['dim yellow bags', 'posh salmon bags']
['dotted maroon bags', 'vibrant red bags']
['mirrored black bags', 'dotted salmon bags', 'pale turquoise bags']


In [788]:
sumations

[50,
 10,
 30,
 60,
 45,
 50,
 0,
 6,
 0,
 0,
 0,
 0,
 225,
 75,
 0,
 250,
 0,
 0,
 600,
 0,
 0,
 225,
 0,
 800,
 0,
 0,
 200,
 0,
 0,
 0,
 150,
 0,
 0,
 0,
 0,
 0,
 200,
 0,
 0,
 0]